[build]
  publish = "public"
  functions = "netlify/functions"
  command = "node inject-env.js"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[build.processing]
  skip_processing = false

[context.production.environment]
  SECRETS_SCAN_OMIT_PATHS = "public/index.html"
